### ISSUE TITLE
Having a hard time posting a cross meme 

### ISSUE THREAD

**Issue by takuminightcore** [oopsie1412/modbot9000#1]
I’m currently having an issue with the bot wizard analyzing video to check to be sure any videos are inappropriate to the discord section I recently tried to post this cross meme from need for speed most wanted but it automatically deleted it because it thought it was inappropriate if can please use this video and try to train the algorithm to allowed this meme To its algorithm https://youtu.be/j4QS2-FnPcE

**Comment by alecagayan** [comment]
that's uh..... not modbot
